"""
Generates a triangle plot (corner plot) from a saved posterior .npz file
using the getdist library.
"""
import argparse
import os
import numpy as np
from getdist import MCSamples
import getdist.plots as gdplt
import matplotlib
import subprocess
matplotlib.use('Agg')
import matplotlib.pyplot as plt
matplotlib.rcParams['text.usetex'] = True
matplotlib.rcParams.update({
'font.size': 20, 
# 'axes.labelsize': 20,
})
matplotlib.rcParams['text.latex.preamble'] = r'\usepackage{amsmath}'
matplotlib.rcParams['text.latex.preamble'] = r'\usepackage{physics}'
params = {'xtick.top': True, 'ytick.right': True, 'xtick.direction': 'in', 'ytick.direction': 'in'}
plt.rcParams.update(params)


# A dictionary to map internal parameter names to clean LaTeX labels for plots
HOD_latex_labels_dict = {
    "logMcut"   : r"\log{M_{\mathrm{cut}}}",
    "logM1"     : r"\log{M_1}",
    "logsigma"  : r"\log\sigma",
    "alpha"     : r"\alpha",
    "alpha_c"   : r"\alpha^{\mathrm{vel}}_{\mathrm{cen}}",
    "alpha_s"   : r"\alpha^{\mathrm{vel}}_{\mathrm{sat}}",
}
cosmo_latex_labels_dict = {
    "Om0"   : r"\Omega_{\mathrm{m0}}",
    "h"     : r"h",
    "S8"    : r"S_8",
    "ns"    : r"n_s",
    "log10fR0abs": r"\log|f_{R0}|",
}
LATEX_LABELS = cosmo_latex_labels_dict | HOD_latex_labels_dict


def load_target_params(target: str = "fid") -> dict:
    Fiducial_params = [
        0.3089,
        0.6774,
        0.8279140636,
        0.9667,
        -5.0, # log10fR0abs
        13.62,
        14.42,
        -0.16020781555467,
        0.9168,
        0.8,
        1.2,
    ] # https://docs.google.com/document/d/1tvrKT6DJ5jcCjoRjGS7GEh7mBsTpu2lGOevDCepjddU/edit?tab=t.0
    # {Omega_b, Omega_m, h, n_s, sigma_8} = {0.0486, 0.3089, 0.6774, 0.9667, 0.8159}
    fiducial_params = {
        'Om0'   : Fiducial_params[0],
        'h'     : Fiducial_params[1],
        'S8'    : Fiducial_params[2],
        'ns'    : Fiducial_params[3],
        'log10fR0abs': Fiducial_params[4],
        'logMcut'   : Fiducial_params[5],
        'logM1'     : Fiducial_params[6],
        'logsigma'  : Fiducial_params[7],
        'alpha'     : Fiducial_params[8],
        'alpha_c'   : Fiducial_params[9],
        'alpha_s'   : Fiducial_params[10],
    }
    return fiducial_params

def create_triangle_plot(npz_path: str, output_path: str):
    """
    Loads posterior samples from an .npz file generated by freyja.mcmc.run_analysis and creates a triangle plot.

    Args:
        npz_path (str): The path to the input .npz file containing posterior samples.
        output_path (str): The path to the output triangle plot .pdf file.
    """
    if not os.path.exists(npz_path):
        raise FileNotFoundError(f"Posterior file not found at: {npz_path}")

    print(f"Loading samples from: {npz_path}")
    data = np.load(npz_path)
    
    samples = data['theta']
    # Ensure names are a standard list of strings
    names = [str(n) for n in data['names']]
    
    # Create the list of LaTeX labels in the correct order
    labels = [LATEX_LABELS.get(name, name) for name in names]

    # Create a getdist MCSamples object
    # This is the core data structure for getdist
    mcsamples = MCSamples(
        samples=samples,
        names=names,
        labels=labels,
        label="Posterior Constraints"
    )

    # Analyze the samples to get convergence stats (optional but good practice)
    stats = mcsamples.getMargeStats()
    summary = mcsamples.getLatex(limit=1)
    print("Convergence stats (R-1):")
    # print(summary)
    _labels, _values = summary
    # Find the length of the longest label for alignment
    max_len = max(len(label) for label in _labels)
    for label, value in zip(_labels, _values):
        print(f"{label:<{max_len}} : {value}")


    for label, params in {
        'cos':  ['Om0', 'h', 'S8', 'ns'],
        'full': ['Om0', 'h', 'S8', 'ns', 'logMcut', 'logM1', 'logsigma', 'alpha', 'alpha_c', 'alpha_s'],
    }.items():
        g = gdplt.getSubplotPlotter()
        g.settings.figure_legend_frame  = False
        g.settings.alpha_filled_add     = 0.6
        g.settings.axes_labelsize       = 32
        g.settings.axes_fontsize        = 24
        g.settings.legend_fontsize      = 24
        # g.settings.subplot_size_ratio     = 1
        # g.settings.axis_tick_max_labels   = 3
        g.settings.axis_marker_lw       = 1.0
        g.settings.axis_marker_color    = "black"
        g.settings.tight_layout         = False

        # Generate the triangle plot
        target_params = load_target_params()
        g.triangle_plot(
            [mcsamples],         # Pass samples as a list
            filled=True,
            params=params,
            # markers=target_params,
        )

        # Add a title with information from the filename
        basename = os.path.basename(npz_path)
        plot_title = os.path.splitext(basename)[0]

        # Define the output filename and save the plot
        output_filename = os.path.splitext(npz_path)[0] + f"_{label}.pdf"
        g.export(output_filename, adir=output_path)
        
        print(f"Triangle plot saved to: {output_filename}")


def cli_entrypoint():
    """Command-line interface for the plotting script."""
    parser = argparse.ArgumentParser(
        description="Generate a triangle plot from Freyja MCMC posterior samples."
    )
    parser.add_argument(
        "posterior_file",
        type=str,
        help="Path to the .npz file containing the posterior samples."
    )
    args = parser.parse_args()
    create_triangle_plot(args.posterior_file)