"""Plot normalized halo scale-dependent bias scans from saved NPZ data.

This script reads the outputs written by ``paper_figs/halo_beta_normalized_data.py``
and makes two separate PDF figures:

1. Fixed cosmology (imodel), fixed M1, varying M2
2. Fixed M1/M2, varying cosmologies

Example
-------
python3 halo_beta_normalized_plots.py
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

import numpy as np
import sys
import h5py
import argparse
from pathlib import Path

import matplotlib
import matplotlib.pyplot as plt
from matplotlib import gridspec
from cycler import cycler
from torch.sparse import mm

matplotlib.use("Agg")
matplotlib.rcParams["text.usetex"] = True
matplotlib.rcParams.update({"font.size": 12})
matplotlib.rcParams["text.latex.preamble"] = r"\usepackage{amsmath}"
matplotlib.rcParams["text.latex.preamble"] = r"\usepackage{physics}"
params = {
    "xtick.top": True,
    "ytick.right": True,
    "xtick.direction": "in",
    "ytick.direction": "in",
}
plt.rcParams.update(params)
custom_cycler = cycler(
    color=[
        "black",
        "lightseagreen",
        "orange",
        "red",
        "darkviolet",
        "mediumblue",
        "green",
    ]
)


def _ensure_repo_on_path() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    repo_root_str = str(repo_root)
    if repo_root_str not in sys.path:
        sys.path.insert(0, repo_root_str)


_ensure_repo_on_path()


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description=(
            "Plot normalized halo beta scans from .npz files generated by "
            "halo_beta_normalized_data.py"
        )
    )
    p.add_argument(
        "--datadir",
        type=Path,
        default=Path("data"),
        help="Directory containing the saved .npz scan files.",
    )
    p.add_argument(
        "--prefix",
        type=str,
        default="halo_beta_normalized",
        help="Filename prefix used by halo_beta_normalized_data.py.",
    )
    p.add_argument(
        "--outdir",
        type=Path,
        default=Path("figs"),
        help="Directory for output PDF figures.",
    )
    p.add_argument(
        "--dpi",
        type=int,
        default=300,
        help="Figure DPI (PDF remains mostly vector).",
    )
    p.add_argument(
        "--legend-ncol",
        type=int,
        default=2,
        help="Legend columns.",
    )
    p.add_argument(
        "--ymin",
        type=float,
        default=None,
        help="Optional y-axis minimum for both plots.",
    )
    p.add_argument(
        "--ymax",
        type=float,
        default=None,
        help="Optional y-axis maximum for both plots.",
    )
    p.add_argument(
        "--reldiff-ylim-pct",
        type=float,
        default=11.0,
        help="Symmetric y-limit (in percent) for the lower relative-difference panel.",
    )
    p.add_argument(
        "--reldiff-mask-min-abs-true",
        type=float,
        default=1.0e-8,
        help="Mask threshold |truth| > threshold for relative-difference panel.",
    )
    return p


def _resolve(path: Path) -> Path:
    p = path.expanduser()
    if not p.is_absolute():
        p = (Path.cwd() / p).resolve()
    return p


def _load_npz(path: Path) -> dict[str, np.ndarray]:
    if not path.exists():
        raise FileNotFoundError(f"Input file not found: {path}")
    with np.load(path, allow_pickle=True) as f:
        return {k: f[k] for k in f.files}


def _apply_plot_style() -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    params = {
        "xtick.top": True,
        "ytick.right": True,
        "xtick.direction": "in",
        "ytick.direction": "in",
        "font.size": 12,
    }
    plt.rcParams.update(params)


def _set_y_limits(ax, ymin: float | None, ymax: float | None) -> None:
    if ymin is None and ymax is None:
        return
    cur = list(ax.get_ylim())
    if ymin is not None:
        cur[0] = float(ymin)
    if ymax is not None:
        cur[1] = float(ymax)
    ax.set_ylim(cur)


def _relative_diff_percent(
    y_emu: np.ndarray, y_true: np.ndarray, min_abs_true: float
) -> np.ndarray:
    y_emu = np.asarray(y_emu, dtype=float)
    y_true = np.asarray(y_true, dtype=float)
    out = np.full_like(y_true, np.nan, dtype=float)
    mask = (
        np.isfinite(y_emu)
        & np.isfinite(y_true)
        & (np.abs(y_true) > float(min_abs_true))
    )
    out[mask] = 100.0 * ((y_emu[mask] / y_true[mask]) - 1.0)
    return out


def plot_fixed_imodel_vary_m2(
    payload: dict[str, np.ndarray],
    *,
    out_path: Path,
    dpi: int = 300,
    legend_ncol: int = 2,
    ymin: float | None = None,
    ymax: float | None = None,
    reldiff_ylim_pct: float = 10.0,
    reldiff_mask_min_abs_true: float = 1.0e-8,
) -> None:
    import matplotlib.pyplot as plt
    from matplotlib import colors as mcolors
    from matplotlib.cm import ScalarMappable

    r = np.asarray(payload["r_bins"], dtype=float)
    b1 = np.asarray(payload["b1"], dtype=float)
    b2_grid = np.asarray(payload["b2_grid"], dtype=float)
    beta_norm_emu = np.asarray(payload["beta_norm_emu"], dtype=float)
    beta_norm_true = np.asarray(payload["beta_norm_true"], dtype=float)
    beta_emu = beta_norm_emu * (b1 * b2_grid[:, None])
    beta_true = beta_norm_true * (b1 * b2_grid[:, None])
    m2_grid = np.asarray(payload["logM2_grid"], dtype=float)
    imodel = int(np.asarray(payload["imodel"]).item())
    m1 = float(np.asarray(payload["logM1"]).item())
    m1_req = float(np.asarray(payload.get("logM1_requested", payload["logM1"])).item())

    if beta_norm_emu.shape != (len(m2_grid), len(r)) or beta_norm_true.shape != (
        len(m2_grid),
        len(r),
    ):
        raise ValueError(
            f"Shape mismatch for fixed-imodel scan: beta_norm_emu {beta_norm_emu.shape}, "
            f"beta_norm_true {beta_norm_true.shape}, "
            f"logM2_grid {m2_grid.shape}, r {r.shape}"
        )

    fig, ax = plt.subplots(
        2,
        1,
        sharex=True,
        figsize=(7, 7),
        gridspec_kw={"height_ratios": [2.5, 1], "hspace": 0},
    )
    cmap = plt.get_cmap("rainbow")
    norm = mcolors.Normalize(vmin=float(np.min(m2_grid)), vmax=float(np.max(m2_grid)))
    line_colors = [cmap(norm(float(m2))) for m2 in m2_grid]

    for i, m2 in enumerate(m2_grid):
        y_emu = beta_emu[i]
        y_true = beta_true[i]
        ax[0].plot(r, y_emu, color=line_colors[i], lw=1.5)
        ax[0].plot(
            r, y_true, color=line_colors[i], lw=0.0, marker="o", ms=2.6, alpha=0.85
        )

        rel_pct = _relative_diff_percent(y_emu, y_true, reldiff_mask_min_abs_true)
        m = np.isfinite(rel_pct)
        if np.any(m):
            ax[1].plot(r[m], rel_pct[m], color=line_colors[i], lw=1.2)

    ax[0].set_xscale("log")
    ax[1].set_xscale("log")
    ax[0].set_ylabel(
        r"$\xi_{{\mathrm{{hh}}}}(r | M_1, M_2) / \xi_{{\mathrm{{mm}}}}(r)$", fontsize=20
    )
    ax[1].set_ylabel(r"$\varepsilon (\%)$", fontsize=20)
    ax[1].set_xlabel(r"$r / (h^{-1}\mathrm{Mpc})$", fontsize=20)
    title = rf"Fixed cosmology (imodel={imodel}), fixed $\log M_1={m1:.2f}$"
    if not np.isclose(m1, m1_req):
        title += rf" (req: {m1_req:.2f})"
    # ax[0].set_title(title + " | lines: emulator, markers: data")
    # ax[0].grid(alpha=0.25, linewidth=0.5)
    # ax[1].grid(alpha=0.25, linewidth=0.5)
    ax[1].axhline(0.0, color="k", ls=":", lw=1.0)
    _set_y_limits(ax[0], ymin, ymax)
    ylim = abs(float(reldiff_ylim_pct))
    ax[1].set_ylim([-ylim, ylim])

    # Encode varying M2 continuously with a rainbow colorbar.
    sm = ScalarMappable(norm=norm, cmap=cmap)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=ax, pad=0.01)
    cbar.set_label(r"$\log_{10} M_2$", fontsize=18)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=int(dpi), bbox_inches="tight", pad_inches=0.05)
    plt.close(fig)


def plot_fixed_masses_vary_cosmology(
    payload: dict[str, np.ndarray],
    *,
    out_path: Path,
    dpi: int = 300,
    legend_ncol: int = 2,
    ymin: float | None = None,
    ymax: float | None = None,
    reldiff_ylim_pct: float = 10.0,
    reldiff_mask_min_abs_true: float = 1.0e-8,
) -> None:
    import matplotlib.pyplot as plt

    r = np.asarray(payload["r_bins"], dtype=float)
    b1 = np.asarray(payload["b1"], dtype=float)
    b2 = np.asarray(payload["b2"], dtype=float)
    beta_norm_emu = np.asarray(payload["beta_norm_emu"], dtype=float)  # (N_imodel, N_r)
    beta_norm_true = np.asarray(
        payload["beta_norm_true"], dtype=float
    )  # (N_imodel, N_r)
    beta_emu = beta_norm_emu * (b1 * b2)[:, None]
    beta_true = beta_norm_true * (b1 * b2)[:, None]
    imodels = np.asarray(payload["imodels"], dtype=int)
    m1 = float(np.asarray(payload["logM1"]).item())
    m2 = float(np.asarray(payload["logM2"]).item())
    m1_req = float(np.asarray(payload.get("logM1_requested", payload["logM1"])).item())
    m2_req = float(np.asarray(payload.get("logM2_requested", payload["logM2"])).item())

    if beta_norm_emu.shape != (len(imodels), len(r)) or beta_norm_true.shape != (
        len(imodels),
        len(r),
    ):
        raise ValueError(
            f"Shape mismatch for fixed-masses scan: beta_norm_emu {beta_norm_emu.shape}, "
            f"beta_norm_true {beta_norm_true.shape}, "
            f"imodels {imodels.shape}, r {r.shape}"
        )

    fig, ax = plt.subplots(
        2,
        1,
        sharex=True,
        figsize=(7, 7),
        gridspec_kw={"height_ratios": [2.5, 1], "hspace": 0},
    )
    for a in ax:
        a.set_prop_cycle(custom_cycler)

    for i, imodel in enumerate(imodels):
        y_emu = beta_emu[i]
        y_true = beta_true[i]
        pp = ax[0].plot(r, y_emu, lw=1.6, label=rf"imodel={int(imodel)}")
        ax[0].plot(
            r, y_true, color=pp[0].get_color(), lw=0.0, marker="o", ms=2.6, alpha=0.85
        )
        rel_pct = _relative_diff_percent(y_emu, y_true, reldiff_mask_min_abs_true)
        m = np.isfinite(rel_pct)
        if np.any(m):
            ax[1].plot(r[m], rel_pct[m], color=pp[0].get_color(), lw=1.2)

    ax[1].set_xscale("log")
    ax[0].set_ylabel(
        r"$\xi_{{\mathrm{{hh}}}}(r | M_1, M_2) / \xi_{{\mathrm{{mm}}}}(r)$",
        fontsize=20,
    )
    ax[1].set_ylabel(r"$\varepsilon (\%)$", fontsize=20)
    ax[1].set_xlabel(r"$r / (h^{-1}\mathrm{Mpc})$", fontsize=20)
    title = (
        rf"Fixed masses: $\log M_1={m1:.2f}$, $\log M_2={m2:.2f}$; varying cosmology"
    )
    if (not np.isclose(m1, m1_req)) or (not np.isclose(m2, m2_req)):
        title += rf" (req: {m1_req:.2f}, {m2_req:.2f})"
    # ax[0].set_title(title + " | lines: emulator, markers: data")
    # ax[0].grid(alpha=0.25, linewidth=0.5)
    # ax[1].grid(alpha=0.25, linewidth=0.5)
    ax[1].axhline(0.0, color="gray", ls="--", lw=0.7)
    _set_y_limits(ax[0], ymin, ymax)
    ylim = abs(float(reldiff_ylim_pct))
    ax[1].set_ylim([-ylim, ylim])
    # ax[0].legend(fontsize=9, ncol=max(1, int(legend_ncol)), loc="best")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=int(dpi), bbox_inches="tight", pad_inches=0.05)
    plt.close(fig)


def main() -> None:
    args = build_parser().parse_args()
    _apply_plot_style()

    datadir = _resolve(args.datadir)
    outdir = _resolve(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    prefix = str(args.prefix)
    file_fixed_imodel = datadir / f"{prefix}_fixed_imodel_m2scan.npz"
    file_fixed_masses = datadir / f"{prefix}_fixed_masses_cosmoscan.npz"

    payload_fixed_imodel = _load_npz(file_fixed_imodel)
    payload_fixed_masses = _load_npz(file_fixed_masses)

    out_fixed_imodel_pdf = outdir / f"{prefix}_fixed_imodel_m2scan.pdf"
    out_fixed_masses_pdf = outdir / f"{prefix}_fixed_masses_cosmoscan.pdf"

    plot_fixed_imodel_vary_m2(
        payload_fixed_imodel,
        out_path=out_fixed_imodel_pdf,
        dpi=int(args.dpi),
        legend_ncol=int(args.legend_ncol),
        ymin=args.ymin,
        ymax=args.ymax,
        reldiff_ylim_pct=float(args.reldiff_ylim_pct),
        reldiff_mask_min_abs_true=float(args.reldiff_mask_min_abs_true),
    )
    print(f"Saved plot: {out_fixed_imodel_pdf}")

    plot_fixed_masses_vary_cosmology(
        payload_fixed_masses,
        out_path=out_fixed_masses_pdf,
        dpi=int(args.dpi),
        legend_ncol=int(args.legend_ncol),
        ymin=args.ymin,
        ymax=args.ymax,
        reldiff_ylim_pct=float(args.reldiff_ylim_pct),
        reldiff_mask_min_abs_true=float(args.reldiff_mask_min_abs_true),
    )
    print(f"Saved plot: {out_fixed_masses_pdf}")


if __name__ == "__main__":
    main()
