"""Load split, reformatted COSMA datasets written under the local ``data/`` folder.

This module provides lightweight APIs for the HDF5 exports generated by
``scripts/reformat_cosma_processed_data.py``. The exported files are split by
property family rather than bundled into a single large container.

The default file naming follows the convention used by the reformat script:

- ``cosmo_params_{gravity}_{dataflag}_z{redshift:.2f}.hdf5``
- ``xiR_hh_diffM_{gravity}_{dataflag}_z{redshift:.2f}.hdf5``
- ``pk_mm_nonlinear_{gravity}_{dataflag}_z{redshift:.2f}.hdf5``
- ``pk_mm_linear_{gravity}_{dataflag}_z{redshift:.2f}.hdf5``
- ``xi_mm_{gravity}_{dataflag}_z{redshift:.2f}.hdf5``
- ``velmom_hh_{gravity}_{dataflag}_z{redshift:.2f}.hdf5``
- ``velmom_hh_transformed_{gravity}_{dataflag}_z{redshift:.2f}.hdf5``

Each file stores one group per model, e.g. ``/model1``, ``/model2``, ..., and
datasets inside each model group.
"""

from __future__ import annotations

from pathlib import Path

import h5py
import numpy as np

DEFAULT_GRAVITY = "LCDM"
DEFAULT_DATAFLAG = "wide_sample_first_64"
DEFAULT_REDSHIFT = 0.25

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DATA_DIR = REPO_ROOT / "data"

_FILENAME_MAP = {
    "cosmo": "cosmo_params_{stem}.hdf5",
    "xihh": "xiR_hh_diffM_{stem}.hdf5",
    "pkmm_nonlinear": "pk_mm_nonlinear_{stem}.hdf5",
    "pkmm_linear": "pk_mm_linear_{stem}.hdf5",
    "ximm": "xi_mm_{stem}.hdf5",
    "velmom": "velmom_hh_{stem}.hdf5",
    "velmom_transformed": "velmom_hh_transformed_{stem}.hdf5",
}


def _file_stem(gravity: str, dataflag: str, redshift: float) -> str:
    """Return the shared filename stem for the split reformatted data files."""
    return f"{gravity}_{dataflag}_z{redshift:.2f}"


def get_reformatted_data_path(
    kind: str,
    gravity: str = DEFAULT_GRAVITY,
    dataflag: str = DEFAULT_DATAFLAG,
    redshift: float = DEFAULT_REDSHIFT,
    data_dir: Path | str = DEFAULT_DATA_DIR,
) -> Path:
    """Return the local HDF5 path for one reformatted COSMA data family.

    Parameters
    ----------
    kind : str
        Data family to load. Supported values are ``"cosmo"``, ``"xihh"``,
        ``"pkmm_nonlinear"``, ``"pkmm_linear"``, ``"ximm"``, ``"velmom"``, and
        ``"velmom_transformed"``.
    gravity : str, optional
        Gravity tag used in the file name. Default is ``"LCDM"``.
    dataflag : str, optional
        Data flag used in the file name. Default is ``"wide_sample_first_64"``.
    redshift : float, optional
        Redshift encoded in the file name. Default is ``0.25``.
    data_dir : Path or str, optional
        Directory containing the split HDF5 files. Default resolves to the
        repository-local ``data/`` directory.

    Returns
    -------
    pathlib.Path
        Path to the requested HDF5 file.

    Raises
    ------
    ValueError
        If ``kind`` is not one of the supported file families.
    """
    if kind not in _FILENAME_MAP:
        supported = ", ".join(sorted(_FILENAME_MAP))
        raise ValueError(f"Unsupported reformatted data kind '{kind}'. Choose from: {supported}")
    stem = _file_stem(gravity=gravity, dataflag=dataflag, redshift=redshift)
    return Path(data_dir) / _FILENAME_MAP[kind].format(stem=stem)


def _read_model_group(
    path: Path,
    imodel: int,
    required_datasets: tuple[str, ...],
) -> tuple[dict[str, object], dict[str, np.ndarray]]:
    """Read one model group and return its attributes plus requested datasets."""
    if not path.exists():
        raise FileNotFoundError(f"Reformatted data file not found: {path}")

    model_key = f"model{int(imodel)}"
    with h5py.File(path, "r") as handle:
        if model_key not in handle:
            raise KeyError(f"Model group '{model_key}' not found in {path}")
        group = handle[model_key]
        data = {}
        for name in required_datasets:
            if name not in group:
                raise KeyError(f"Dataset '{name}' not found in {path}:{model_key}")
            data[name] = group[name][...]
        attrs = dict(group.attrs.items())
    return attrs, data


def load_reformatted_cosmology(
    imodel: int,
    gravity: str = DEFAULT_GRAVITY,
    dataflag: str = DEFAULT_DATAFLAG,
    redshift: float = DEFAULT_REDSHIFT,
    data_dir: Path | str = DEFAULT_DATA_DIR,
) -> np.ndarray:
    """Load the reformatted cosmology vector ``[Om0, h, S8, ns]`` for one model.

    Parameters
    ----------
    imodel : int
        Cosmology index stored in the split export file.
    gravity, dataflag, redshift, data_dir
        File-selection parameters. Together they identify the exported HDF5
        file to read from.

    Returns
    -------
    np.ndarray
        One-dimensional array containing ``[Om0, h, S8, ns]``.
    """
    path = get_reformatted_data_path(
        "cosmo", gravity=gravity, dataflag=dataflag, redshift=redshift, data_dir=data_dir
    )
    _, data = _read_model_group(path, imodel, ("cosmo_params",))
    return np.asarray(data["cosmo_params"], dtype=float)


def load_reformatted_xihh(
    imodel: int,
    gravity: str = DEFAULT_GRAVITY,
    dataflag: str = DEFAULT_DATAFLAG,
    redshift: float = DEFAULT_REDSHIFT,
    data_dir: Path | str = DEFAULT_DATA_DIR,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Load reformatted halo-halo correlation data for one model.

    Returns
    -------
    tuple of np.ndarray
        ``(r, logM_bins, xi_hh, xi_sem)`` where ``xi_hh`` and ``xi_sem`` have
        shape ``(N_M, N_M, N_r)``.
    """
    path = get_reformatted_data_path(
        "xihh", gravity=gravity, dataflag=dataflag, redshift=redshift, data_dir=data_dir
    )
    _, data = _read_model_group(path, imodel, ("r", "logM_bins", "xi_hh", "xi_sem"))
    return (
        np.asarray(data["r"], dtype=float),
        np.asarray(data["logM_bins"], dtype=float),
        np.asarray(data["xi_hh"], dtype=float),
        np.asarray(data["xi_sem"], dtype=float),
    )


def load_reformatted_pkmm_nonlinear(
    imodel: int,
    gravity: str = DEFAULT_GRAVITY,
    dataflag: str = DEFAULT_DATAFLAG,
    redshift: float = DEFAULT_REDSHIFT,
    data_dir: Path | str = DEFAULT_DATA_DIR,
    return_boxes: bool = False,
) -> tuple[np.ndarray, np.ndarray] | tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Load reformatted nonlinear matter power-spectrum data for one model.

    Parameters
    ----------
    return_boxes : bool, optional
        If ``True``, also return ``pkmm_boxes`` from the file. This requires the
        export script to have been run with ``--include-pk-boxes``.

    Returns
    -------
    tuple
        Returns ``(k, pkmm_mean)`` by default. If ``return_boxes`` is ``True``,
        returns ``(k, pkmm_mean, pkmm_boxes)``.
    """
    path = get_reformatted_data_path(
        "pkmm_nonlinear",
        gravity=gravity,
        dataflag=dataflag,
        redshift=redshift,
        data_dir=data_dir,
    )
    datasets = ("k", "pkmm_mean") + (("pkmm_boxes",) if return_boxes else ())
    _, data = _read_model_group(path, imodel, datasets)
    k = np.asarray(data["k"], dtype=float)
    pkmm_mean = np.asarray(data["pkmm_mean"], dtype=float)
    if not return_boxes:
        return k, pkmm_mean
    return k, pkmm_mean, np.asarray(data["pkmm_boxes"], dtype=float)


def load_reformatted_pkmm_linear(
    imodel: int,
    gravity: str = DEFAULT_GRAVITY,
    dataflag: str = DEFAULT_DATAFLAG,
    redshift: float = DEFAULT_REDSHIFT,
    data_dir: Path | str = DEFAULT_DATA_DIR,
) -> tuple[np.ndarray, np.ndarray]:
    """Load reformatted linear matter power-spectrum data for one model.

    Returns
    -------
    tuple of np.ndarray
        ``(k, pkmm_linear)``.
    """
    path = get_reformatted_data_path(
        "pkmm_linear",
        gravity=gravity,
        dataflag=dataflag,
        redshift=redshift,
        data_dir=data_dir,
    )
    attrs, data = _read_model_group(path, imodel, tuple())
    if attrs.get("missing", False):
        reason = attrs.get("missing_reason", "missing data")
        raise KeyError(f"Linear matter power spectrum unavailable for model{imodel}: {reason}")
    _, data = _read_model_group(path, imodel, ("k", "pkmm_linear"))
    return np.asarray(data["k"], dtype=float), np.asarray(data["pkmm_linear"], dtype=float)


def load_reformatted_ximm(
    imodel: int,
    gravity: str = DEFAULT_GRAVITY,
    dataflag: str = DEFAULT_DATAFLAG,
    redshift: float = DEFAULT_REDSHIFT,
    data_dir: Path | str = DEFAULT_DATA_DIR,
) -> tuple[np.ndarray, np.ndarray]:
    """Load reformatted matter correlation-function data for one model.

    Returns
    -------
    tuple of np.ndarray
        ``(r, xi_mm)`` where ``xi_mm`` is defined on the same ``r`` grid used by
        the reformatted halo-halo correlation file.
    """
    path = get_reformatted_data_path(
        "ximm", gravity=gravity, dataflag=dataflag, redshift=redshift, data_dir=data_dir
    )
    _, data = _read_model_group(path, imodel, ("r", "ximm"))
    return np.asarray(data["r"], dtype=float), np.asarray(data["ximm"], dtype=float)


def load_reformatted_velocity_moments(
    imodel: int,
    gravity: str = DEFAULT_GRAVITY,
    dataflag: str = DEFAULT_DATAFLAG,
    redshift: float = DEFAULT_REDSHIFT,
    data_dir: Path | str = DEFAULT_DATA_DIR,
) -> dict[str, np.ndarray]:
    """Load reformatted raw halo velocity-moment grids for one model.

    Returns
    -------
    dict[str, np.ndarray]
        Dictionary containing ``r``, ``logM_bins``, the raw moments
        ``m10, c20, c02, c30, c12, c40, c22, c04``, and the corresponding SEM
        arrays ``*_err``.
    """
    path = get_reformatted_data_path(
        "velmom", gravity=gravity, dataflag=dataflag, redshift=redshift, data_dir=data_dir
    )
    keys = (
        "r",
        "logM_bins",
        "m10",
        "c20",
        "c02",
        "c30",
        "c12",
        "c40",
        "c22",
        "c04",
        "m10_err",
        "c20_err",
        "c02_err",
        "c30_err",
        "c12_err",
        "c40_err",
        "c22_err",
        "c04_err",
    )
    _, data = _read_model_group(path, imodel, keys)
    return {key: np.asarray(value, dtype=float) for key, value in data.items()}


def load_reformatted_velocity_moments_transformed(
    imodel: int,
    gravity: str = DEFAULT_GRAVITY,
    dataflag: str = DEFAULT_DATAFLAG,
    redshift: float = DEFAULT_REDSHIFT,
    data_dir: Path | str = DEFAULT_DATA_DIR,
) -> dict[str, np.ndarray]:
    """Load reformatted transformed halo velocity-moment grids for one model.

    This API targets the optional transformed export written by
    ``scripts/reformat_cosma_processed_data.py --include-transformed-velmom``.

    Returns
    -------
    dict[str, np.ndarray]
        Dictionary containing ``r``, ``logM_bins``, ``m10_linear``, and the
        transformed moment arrays.
    """
    path = get_reformatted_data_path(
        "velmom_transformed",
        gravity=gravity,
        dataflag=dataflag,
        redshift=redshift,
        data_dir=data_dir,
    )
    keys = (
        "r",
        "logM_bins",
        "m10_linear",
        "m10_transformed",
        "c20_transformed",
        "c02_transformed",
        "c30_transformed",
        "c12_transformed",
        "c40_transformed",
        "c22_transformed",
        "c04_transformed",
    )
    _, data = _read_model_group(path, imodel, keys)
    return {key: np.asarray(value, dtype=float) for key, value in data.items()}


__all__ = [
    "DEFAULT_DATA_DIR",
    "DEFAULT_DATAFLAG",
    "DEFAULT_GRAVITY",
    "DEFAULT_REDSHIFT",
    "get_reformatted_data_path",
    "load_reformatted_cosmology",
    "load_reformatted_pkmm_linear",
    "load_reformatted_pkmm_nonlinear",
    "load_reformatted_velocity_moments",
    "load_reformatted_velocity_moments_transformed",
    "load_reformatted_xihh",
    "load_reformatted_ximm",
]
